// Code generated by raiden-cli; DO NOT EDIT.
package bootstrap

import (
	"github.com/sev-2/raiden"
	"medpoint/internal/controllers"
	"medpoint/internal/models"
	"github.com/valyala/fasthttp"
)

func RegisterRoute(server *raiden.Server) {
	server.RegisterRoute([]*raiden.Route{
		{
			Type:       raiden.RouteTypeCustom,
			Path:       "/rest/v1/medpointdoctor?select=*&id=eq.1",
			Methods:    []string{fasthttp.MethodGet},
			Controller: &controllers.HelloWordController{},
		},
		{
			Type:       raiden.RouteTypeRest,
			Path:       "/rest/v1/medpointdoctor",
			Methods:    []string{},
			Controller: &controllers.BooksController{},
			Model:      models.MedpointDoctor{},
		},
	})
}
